[package]
name = "ultraviolet-glm-test"
version = "0.1.0"
authors = ["jaynus <jaynus@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ultraviolet = "*"
approx = "*"

[build-dependencies]
cmake = "0.1.42"
